//
// Created by proszkowski on 25.05.2022.
//

#ifndef AMCT_EXAMPLE_QUEUE_LOGGERPORT_H
#define AMCT_EXAMPLE_QUEUE_LOGGERPORT_H

#include <stdbool.h>
#include "queue_makePortsMacros.h"

QUEUE_STATIC_CREATE_PORT_HEADER(example1)
QUEUE_STATIC_PUT_PORT_HEADER(example1)
QUEUE_STATIC_GET_PORT_HEADER(example1)
QUEUE_STATIC_GET_MAX_DEPTH_PORT_HEADER(example1)

#endif //AMCT_EXAMPLE_QUEUE_LOGGERPORT_H
