//
// Created by proszkowski on 25.05.2022.
//

#include <stdlib.h>
#include "queue_example1Port.h"

#define EXAMPLE1_QUE_LEN (2048+1) //Actually queue is able to store one element less

QUEUE_STATIC_ALLOCATION(example1, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_CREATE_PORT(example1, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_PUT_PORT(example1)
QUEUE_STATIC_GET_PORT(example1)
QUEUE_STATIC_GET_MAX_DEPTH_PORT(example1)

QUEUE_STATIC_ALLOCATION(example1rx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_CREATE_PORT(example1rx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_PUT_PORT(example1rx)
QUEUE_STATIC_GET_PORT(example1rx)
QUEUE_STATIC_GET_MAX_DEPTH_PORT(example1rx)

QUEUE_STATIC_ALLOCATION(uart1tx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_CREATE_PORT(uart1tx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_PUT_PORT(uart1tx)
QUEUE_STATIC_GET_PORT(uart1tx)
QUEUE_STATIC_GET_MAX_DEPTH_PORT(uart1tx)

QUEUE_STATIC_ALLOCATION(uart1rx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_CREATE_PORT(uart1rx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_PUT_PORT(uart1rx)
QUEUE_STATIC_GET_PORT(uart1rx)
QUEUE_STATIC_GET_MAX_DEPTH_PORT(uart1rx)

QUEUE_STATIC_ALLOCATION(uart3tx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_CREATE_PORT(uart3tx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_PUT_PORT(uart3tx)
QUEUE_STATIC_GET_PORT(uart3tx)
QUEUE_STATIC_GET_MAX_DEPTH_PORT(uart3tx)

QUEUE_STATIC_ALLOCATION(uart3rx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_CREATE_PORT(uart3rx, 1, EXAMPLE1_QUE_LEN)
QUEUE_STATIC_PUT_PORT(uart3rx)
QUEUE_STATIC_GET_PORT(uart3rx)
QUEUE_STATIC_GET_MAX_DEPTH_PORT(uart3rx)